version: "3.7"
services:
  rocket-name:
    image: foxundermoon/rocketmq-3.2.6
    command:
      - sh
      - /app/bin/mqnamesrv
    networks:
      - rocket
  rocket-broker:
    image:  foxundermoon/rocketmq-3.2.6
    command:
      - sh
      - "-c"
      - "echo  brokerIP1=$$(wget -qO- ip.sb) >> /app/conf/broker.properties && sh /app/bin/mqbroker -n localhost:9876 -c /app/conf/broker.properties"
    networks:
      - rocket

networks:
  rocket:
    external: true
    name: host