version: "3.7"
services:
  rocket-name:
    image: foxundermoon/rocketmq-3.2.6
    command:
      - sh
      - /app/bin/mqnamesrv
    networks:
      - rocket
  rocket-broker:
    image:  foxundermoon/rocketmq-3.2.6
    command: sh /app/bin/mqbroker -n localhost:9876
    networks:
      - rocket

networks:
  rocket:
    external: true
    name: host